apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress 
spec:
  selector:
    matchLabels:
      app: wordpress
      version: v1
  replicas: 1 # tells deployment to run 2 pods matching the template
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: wordpress
        version: v1
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: 192.168.2.11
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        hostPath:
          path: /nfsdata/k8s/wordpress
